volumes:
  users-vol:
  uploads-vol:

services:

  pgsql:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - users-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

  python:
    image: nostalgiacode/test:0.1.0.RELEASE
    depends_on:
      - pgsql
    volumes:
      - uploads-vol:/app/uploads
    ports:
      - 80:5000